version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /third_party/zlib/contrib/dotzlib/DotZLib
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /third_party/java/proguard/proguard6.2.2/buildscripts
    schedule:
      interval: daily
