steps:
 - label: "Ubuntu 14.04"
   command: "echo '--- Cleanup'\n
      bazel clean --expunge\n

      echo '--- Setup'\n
      cat >> WORKSPACE << EOF
android_sdk_repository(
    name = \"androidsdk\",
    path = \"${ANDROID_SDK_PATH}\",
)

android_ndk_repository(
    name = \"androidndk\",
    path = \"${ANDROID_NDK_PATH}\",
)\nEOF\n

      echo '+++ Building'\n
      bazel build --color=yes //src:bazel\n//scripts/...\n

      echo '+++ Testing'\n
      bazel test //scripts/... //src/test/... //third_party/ijar/... //tools/android/...\n"
   agents:
     - "os=ubuntu1404"

 - label: "Ubuntu 16.04"
   command: "echo '--- Cleanup'\n
      bazel clean --expunge\n

      echo '--- Setup'\n
      cat >> WORKSPACE << EOF
android_sdk_repository(
    name = \"androidsdk\",
    path = \"${ANDROID_SDK_PATH}\",
)

android_ndk_repository(
    name = \"androidndk\",
    path = \"${ANDROID_NDK_PATH}\",
)
EOF\n

      echo '+++ Building'\n
      bazel build --color=yes //src:bazel\n//scripts/...

      echo '+++ Testing'\n
      bazel test //scripts/... //src/test/... //third_party/ijar/... //tools/android/...\n"
   agents:
     - "os=ubuntu1604"
