steps:
#  - command: "buildkite-agent pipeline upload"
#    label: ":pipeline:"
  - command: "install_bazel.sh"
    label: ":install bazelisk:"
  - command: "bazel build //..."
    label: ":bazel: Build"
