steps:
#  - command: "buildkite-agent pipeline upload"
#    label: ":pipeline:"
  - command: "install_bazel.sh"
    key: "install_bazel"
  - command: "bazel build //..."
    key: "bazel_build"
    depends_on: "install_bazel"
    retry:
      automatic: true
