steps:
  - commands:
    - "install_bazel.sh"
    - "bazel build //src:bazel-dev"
    key: "bazel_build"
    label: "bazel"
  - command: "bazel test //src/test/..."
    key: "bazel_test"
    depends_on: "bazel_build"
