name: Label & Comment on Approved PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pullRequest = context.payload.pull_request;
            const approvedReview = pullRequest.reviews.find(review => review.state === 'APPROVED' && review.user.login === github.actor);

            if (approvedReview) {
              const daysSinceApproval = Math.floor((new Date() - new Date(approvedReview.submitted_at)) / (1000 * 60 * 60 * 24));

              if (daysSinceApproval > 0 && pullRequest.labels.some(label => label.name === 'awaiting-review')) {
                // Check if the comment has already been posted
                const comments = await github.issues.listComments({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pullRequest.number
                });

                const hasComment = comments.data.some(comment => comment.body.includes('This PR has been approved for more than 5 days and still has the \'awaiting-review\' label applied'));

                if (!hasComment) {
                  await github.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pullRequest.number,
                    body: `This PR has been approved for more than 5 days and still has the 'awaiting-review' label applied. If this has been reviewed and you’d like the PR to be imported, please apply the 'awaiting-pr-merge' label, or remove 'awaiting-PR-merge' label to import directly.`
                  });
                }
              }
            }
