name: Label & Comment on Approved PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get GitHub Pull Request Reviewers
        id: reviews
      - uses: LiamPerson/get-reviews-action@SPECIFY_ME
      - name: Consumes reviews
        uses: some/workflow@version
        with:
          RELEASES_JSON_FILE: ${{ steps.reviews.outputs.reviews_file_path }}
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
                env:
                requested_reviewers: ${{ toJson(github.event.pull_request.requested_reviewers) }}
                github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: `Hi @{requested_reviewers}, Since the PR has been approved. Please confirm if the approved PR should be internally merged! `
                })
                github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: ['awaiting-PR-merge']
                })
