name: Label & Comment on Approved PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get GitHub Pull Request Reviewers
        uses: LiamPerson/get-reviews-action@v1.1.2  # Replace with desired version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Filter Approved Reviewers
        run: |
          approved_reviewers=$(cat reviews.json | jq -r '.reviews[] | select(.state == "APPROVED") | .user.login')
          echo "requested_reviewers=${approved_reviewers}" >> $GITHUB_ENV
          
      - uses: actions/github-script@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          script: |
                env:
                github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: `Hi @{approved_reviewers}, Since the PR has been approved. Please confirm if the approved PR should be internally merged! `
                })
                github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: ['awaiting-PR-merge']
                })
