name: release-helper
on:
  issue_comment:
    types: [created, edited]
permissions:
  contents: read

jobs:
  release-helper:
    if: startsWith(github.event.comment.body, '@bazel-io ')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Run helper
        uses: bazelbuild/continuous-integration/actions/release-helper@70ab2cc80222b90afde06fa0b3b7c067239777b4 # master
        with:
          token: ${{ secrets.BAZEL_IO_TOKEN }}
